const cmjDb=supabase.createClient(window.CMJ_SUPABASE_URL,window.CMJ_SUPABASE_KEY);
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function frDate(v){return new Intl.DateTimeFormat('fr-FR',{dateStyle:'long',timeStyle:'short'}).format(new Date(v));}
function setMsg(el,msg,type='ok'){if(!el)return;el.textContent=msg;el.className='form-message '+type;}
async function uploadMedia(file,prefix){if(!file||!file.size)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${prefix}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await cmjDb.storage.from('cmj-media').upload(path,file,{upsert:false});if(error)throw error;return cmjDb.storage.from('cmj-media').getPublicUrl(path).data.publicUrl;}

async function initApplications(){const form=document.querySelector('#cmj-application');if(!form)return;const msg=document.querySelector('#application-message');form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const {error}=await cmjDb.from('cmj_applications').insert({first_name:fd.get('prenom'),last_name:fd.get('nom'),birthdate:fd.get('naissance'),school:fd.get('ecole')||null,address:fd.get('adresse'),guardian_email:fd.get('email'),guardian_phone:fd.get('telephone'),motivation:fd.get('motivation'),consent:true,status:'new'});if(error)return setMsg(msg,"Impossible d'envoyer la candidature.",'error');form.reset();setMsg(msg,'Candidature envoyée avec succès.');});}

async function initEvents(){const root=document.querySelector('#events-list');if(!root)return;const {data,error}=await cmjDb.rpc('list_public_events');if(error){root.innerHTML='<div class="notice">Impossible de charger les événements.</div>';return;}if(!data?.length){root.innerHTML='<div class="notice">Aucun événement ouvert pour le moment.</div>';return;}root.innerHTML=data.map(ev=>{const full=ev.capacity!==null&&Number(ev.remaining_places)<=0;const deadline=ev.registration_deadline&&new Date(ev.registration_deadline)<new Date();const closed=full||deadline;const places=ev.capacity===null?'Places non limitées':`${ev.remaining_places} place(s) restante(s) sur ${ev.capacity}`;const visual=ev.image_url?`<div class="event-visual event-image"><img src="${esc(ev.image_url)}" alt=""></div>`:'<div class="event-visual">📅</div>';return `<article class="event-card" data-event="${ev.id}">${visual}<div class="event-content"><span class="event-date">${esc(frDate(ev.event_date))}</span><h2>${esc(ev.title)}</h2><p>${esc(ev.description)}</p><div class="event-meta"><span>📍 ${esc(ev.location||'Lieu à préciser')}</span><span>👥 ${esc(places)}</span></div><button class="btn primary event-register-toggle" ${closed?'disabled':''}>${closed?'Inscriptions fermées':"S'inscrire"}</button><form class="form-grid event-register-form" hidden><div class="two-col"><label>Prénom<input required name="first"></label><label>Nom<input required name="last"></label></div><label>Date de naissance<input type="date" name="birth"></label><label>Responsable légal<input name="guardian"></label><div class="two-col"><label>E-mail<input required type="email" name="email"></label><label>Téléphone<input type="tel" name="phone"></label></div><label>Informations utiles<textarea name="notes"></textarea></label><label class="consent"><input required type="checkbox"> J'autorise l'utilisation de ces informations pour gérer cette inscription.</label><button class="btn primary">Confirmer l'inscription</button><p class="form-message"></p></form></div></article>`}).join('');root.querySelectorAll('.event-register-toggle').forEach(b=>b.onclick=()=>{const f=b.closest('.event-content').querySelector('.event-register-form');f.hidden=!f.hidden;});root.querySelectorAll('.event-register-form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),msg=f.querySelector('.form-message');const {error}=await cmjDb.from('event_registrations').insert({event_id:f.closest('.event-card').dataset.event,participant_first_name:fd.get('first'),participant_last_name:fd.get('last'),participant_birthdate:fd.get('birth')||null,guardian_name:fd.get('guardian')||null,guardian_email:fd.get('email'),guardian_phone:fd.get('phone')||null,notes:fd.get('notes')||null,consent:true});if(error)return setMsg(msg,error.message.includes('EVENT_FULL')?'Événement complet.':"Impossible d'enregistrer l'inscription.",'error');f.reset();setMsg(msg,'Inscription enregistrée.');});}

async function initProjects(){const root=document.querySelector('#projects-list');if(!root)return;const {data,error}=await cmjDb.from('projects').select('*').in('status',['published','completed']).order('created_at',{ascending:false});if(error){root.innerHTML='<div class="notice">Impossible de charger les projets.</div>';return;}if(!data?.length){root.innerHTML='<div class="notice">Aucun projet publié pour le moment.</div>';return;}root.innerHTML=data.map(p=>`<article>${p.image_url?`<div class="pic project-photo"><img src="${esc(p.image_url)}" alt=""></div>`:'<div class="pic">💡</div>'}<small>${p.status==='completed'?'RÉALISÉ':'PROJET'}</small><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><b>● ${p.status==='completed'?'Réalisé':'Publié'}</b></article>`).join('');}

async function getPerms(){const {data,error}=await cmjDb.rpc('get_my_admin_permissions');return error||!data?.[0]?null:data[0];}
function allowed(p,key){return !!(p&&(p.is_super_admin||p['can_manage_'+key]));}
async function initAdmin(){const login=document.querySelector('#admin-login');if(!login)return;const dash=document.querySelector('#admin-dashboard'),msg=document.querySelector('#admin-login-message');async function refresh(){const {data:{session}}=await cmjDb.auth.getSession();const p=session?await getPerms():null;login.hidden=!!p;dash.hidden=!p;if(p){applyPerms(p);await bindAdmin(p);await loadAdmin(p);}}document.querySelector('#admin-signin').onclick=async()=>{const {error}=await cmjDb.auth.signInWithPassword({email:document.querySelector('#admin-email').value.trim(),password:document.querySelector('#admin-password').value});if(error)return setMsg(msg,'Connexion impossible : vérifie tes identifiants.','error');const p=await getPerms();if(!p){await cmjDb.auth.signOut();return setMsg(msg,"Ce compte n'est pas autorisé.",'error');}await refresh();};document.querySelector('#admin-logout').onclick=async()=>{await cmjDb.auth.signOut();location.reload();};await refresh();}
function applyPerms(p){document.querySelector('#admin-identity').textContent=`Connecté : ${p.display_name||p.email}`;document.querySelectorAll('[data-perm]').forEach(el=>el.hidden=!allowed(p,el.dataset.perm));}
async function bindAdmin(p){const ev=document.querySelector('#event-create-form');if(ev&&!ev.dataset.bound){ev.dataset.bound=1;ev.onsubmit=async e=>{e.preventDefault();const fd=new FormData(ev),m=document.querySelector('#event-create-message');try{const image=allowed(p,'media')?await uploadMedia(fd.get('image'),'events'):null;const {error}=await cmjDb.from('events').insert({title:fd.get('title'),description:fd.get('description'),event_date:new Date(fd.get('date')).toISOString(),location:fd.get('location'),capacity:fd.get('capacity')?Number(fd.get('capacity')):null,registration_deadline:fd.get('deadline')?new Date(fd.get('deadline')).toISOString():null,image_url:image,status:fd.get('status')});if(error)throw error;ev.reset();setMsg(m,'Événement enregistré.');await loadAdmin(p);}catch(err){setMsg(m,err.message||'Erreur','error');}}}
const pr=document.querySelector('#project-create-form');if(pr&&!pr.dataset.bound){pr.dataset.bound=1;pr.onsubmit=async e=>{e.preventDefault();const fd=new FormData(pr),m=document.querySelector('#project-create-message');try{const image=allowed(p,'media')?await uploadMedia(fd.get('image'),'projects'):null;const {error}=await cmjDb.from('projects').insert({title:fd.get('title'),description:fd.get('description'),image_url:image,status:fd.get('status')});if(error)throw error;pr.reset();setMsg(m,'Projet enregistré.');await loadAdmin(p);}catch(err){setMsg(m,err.message||'Erreur','error');}}}
const af=document.querySelector('#admin-create-form');if(af&&!af.dataset.bound){af.dataset.bound=1;af.onsubmit=async e=>{e.preventDefault();const fd=new FormData(af),m=document.querySelector('#admin-create-message');const body={action:'create',display_name:fd.get('display_name'),email:fd.get('email'),password:fd.get('password'),is_super_admin:fd.get('super')==='on',can_manage_admins:fd.get('admins')==='on',can_manage_events:fd.get('events')==='on',can_manage_projects:fd.get('projects')==='on',can_manage_applications:fd.get('applications')==='on',can_manage_registrations:fd.get('registrations')==='on',can_manage_media:fd.get('media')==='on'};const {data,error}=await cmjDb.functions.invoke('manage-admins',{body});if(error||data?.error)return setMsg(m,data?.error||error.message,'error');af.reset();setMsg(m,'Compte admin créé.');await loadAdmins();};}}
async function loadAdmin(p){if(allowed(p,'events')){const {data=[]}=await cmjDb.from('events').select('*').order('event_date');const box=document.querySelector('#admin-events');box.innerHTML=data.map(e=>`<div class="admin-row"><div>${e.image_url?`<img class="admin-thumb" src="${esc(e.image_url)}">`:''}<strong>${esc(e.title)}</strong><small>${esc(frDate(e.event_date))} • ${esc(e.status)}</small></div><div><button class="small-btn" data-close-event="${e.id}">Fermer</button> <button class="small-btn danger" data-del-event="${e.id}">Supprimer</button></div></div>`).join('')||'<p>Aucun événement.</p>';box.querySelectorAll('[data-close-event]').forEach(b=>b.onclick=async()=>{await cmjDb.from('events').update({status:'closed'}).eq('id',b.dataset.closeEvent);await loadAdmin(p);});box.querySelectorAll('[data-del-event]').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer cet événement et ses inscriptions ?')){await cmjDb.from('events').delete().eq('id',b.dataset.delEvent);await loadAdmin(p);}});}
if(allowed(p,'projects')){const {data=[]}=await cmjDb.from('projects').select('*').order('created_at',{ascending:false});const box=document.querySelector('#admin-projects');box.innerHTML=data.map(x=>`<div class="admin-row"><div>${x.image_url?`<img class="admin-thumb" src="${esc(x.image_url)}">`:''}<strong>${esc(x.title)}</strong><small>${esc(x.status)}</small></div><button class="small-btn danger" data-del-project="${x.id}">Supprimer</button></div>`).join('')||'<p>Aucun projet.</p>';box.querySelectorAll('[data-del-project]').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer ce projet ?')){await cmjDb.from('projects').delete().eq('id',b.dataset.delProject);await loadAdmin(p);}});}
if(allowed(p,'applications')){const {data=[]}=await cmjDb.from('cmj_applications').select('*').order('created_at',{ascending:false});const box=document.querySelector('#admin-applications');box.innerHTML=data.map(a=>`<div class="admin-row"><div><strong>${esc(a.first_name)} ${esc(a.last_name)}</strong><small>${esc(a.guardian_email)} • ${esc(a.guardian_phone)}</small><p>${esc(a.motivation)}</p></div><button class="small-btn danger" data-del-app="${a.id}">Supprimer</button></div>`).join('')||'<p>Aucune candidature.</p>';box.querySelectorAll('[data-del-app]').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer cette candidature ?')){await cmjDb.from('cmj_applications').delete().eq('id',b.dataset.delApp);await loadAdmin(p);}});}
if(allowed(p,'registrations')){const {data=[]}=await cmjDb.from('event_registrations').select('*,events(title)').order('created_at',{ascending:false});const box=document.querySelector('#admin-registrations');box.innerHTML=data.map(r=>`<div class="admin-row"><div><strong>${esc(r.participant_first_name)} ${esc(r.participant_last_name)}</strong><small>${esc(r.events?.title||'Événement')} • ${esc(r.guardian_email)}</small></div><button class="small-btn danger" data-del-reg="${r.id}">Supprimer</button></div>`).join('')||'<p>Aucune inscription.</p>';box.querySelectorAll('[data-del-reg]').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer cette inscription ?')){await cmjDb.from('event_registrations').delete().eq('id',b.dataset.delReg);await loadAdmin(p);}});}
if(allowed(p,'admins'))await loadAdmins();}
async function loadAdmins(){const box=document.querySelector('#admin-users');if(!box)return;const {data,error}=await cmjDb.functions.invoke('manage-admins',{body:{action:'list'}});if(error||data?.error){box.innerHTML='<p>Impossible de charger les admins.</p>';return;}box.innerHTML=(data.admins||[]).map(a=>`<div class="admin-row admin-user" data-admin-id="${a.id}"><div><strong>${esc(a.display_name||a.email)}</strong><small>${esc(a.email)}${a.is_super_admin?' • SUPER-ADMIN':''}</small><div class="permission-badges">${a.is_super_admin?'<span>Tous les droits</span>':['events','projects','applications','registrations','media','admins'].filter(k=>a['can_manage_'+k]).map(k=>`<span>${k}</span>`).join('')}</div></div><button class="small-btn danger" data-del-admin="${a.id}">Supprimer</button></div>`).join('');box.querySelectorAll('[data-del-admin]').forEach(b=>b.onclick=async()=>{if(!confirm('Supprimer ce compte administrateur ?'))return;const {data,error}=await cmjDb.functions.invoke('manage-admins',{body:{action:'delete',id:b.dataset.delAdmin}});if(error||data?.error)return alert(data?.error||error.message);await loadAdmins();});}

document.addEventListener('DOMContentLoaded',()=>{initApplications();initEvents();initProjects();initAdmin();});