const featureDb=supabase.createClient(window.CMJ_SUPABASE_URL,window.CMJ_SUPABASE_KEY);
const fEsc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

async function initIdeaBox(){const form=document.querySelector('#idea-form');if(!form)return;const msg=document.querySelector('#idea-message');form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const {error}=await featureDb.from('ideas').insert({first_name:fd.get('first_name')||null,age:fd.get('age')?Number(fd.get('age')):null,email:fd.get('email')||null,category:fd.get('category')||'Autre',title:fd.get('title'),description:fd.get('description'),consent:true,status:'new'});if(error){msg.textContent="Impossible d'envoyer l'idée pour le moment.";msg.className='form-message error';return;}form.reset();msg.textContent='Merci ! Ton idée a bien été envoyée au CMJ.';msg.className='form-message';});}

async function initCalendar(){const root=document.querySelector('#calendar-list');if(!root)return;const {data,error}=await featureDb.rpc('list_public_events');if(error){root.innerHTML='<div class="notice">Impossible de charger le calendrier.</div>';return;}const future=(data||[]).filter(e=>new Date(e.event_date)>=new Date()).slice(0,30);if(!future.length){root.innerHTML='<div class="notice">Aucune date programmée pour le moment.</div>';return;}root.innerHTML=future.map(e=>{const d=new Date(e.event_date);const day=String(d.getDate()).padStart(2,'0');const mon=new Intl.DateTimeFormat('fr-FR',{month:'short'}).format(d);const time=new Intl.DateTimeFormat('fr-FR',{hour:'2-digit',minute:'2-digit'}).format(d);return `<article class="calendar-item"><div class="calendar-date"><strong>${day}</strong><span>${fEsc(mon)}</span></div><div><h3>${fEsc(e.title)}</h3><p>${fEsc(e.description)}</p><div class="calendar-meta"><span>🕒 ${fEsc(time)}</span><span>📍 ${fEsc(e.location||'Lieu à préciser')}</span></div><a class="btn outline" style="margin-top:14px" href="evenements.html">Voir l'événement</a></div></article>`}).join('');if(document.documentElement.classList.contains('motion-ok')){root.querySelectorAll('.calendar-item').forEach((el,i)=>{el.classList.add('reveal-item');setTimeout(()=>el.classList.add('is-visible'),80+i*70);});}}

function injectAdminExtras(){const dash=document.querySelector('#admin-dashboard');if(!dash||document.querySelector('#admin-stats'))return;const top=dash.querySelector('.admin-top');const stats=document.createElement('section');stats.id='admin-stats';stats.className='stats-grid';stats.innerHTML='<div class="stat-card"><strong id="stat-events">–</strong><span>Événements</span></div><div class="stat-card"><strong id="stat-projects">–</strong><span>Projets</span></div><div class="stat-card"><strong id="stat-registrations">–</strong><span>Inscriptions</span></div><div class="stat-card"><strong id="stat-ideas">–</strong><span>Idées reçues</span></div>';top.after(stats);const ideas=document.createElement('section');ideas.className='panel admin-section';ideas.innerHTML='<h2>💡 Boîte à idées</h2><p>Les propositions envoyées depuis le site apparaissent ici.</p><div id="admin-ideas" class="admin-list"><p>Chargement…</p></div>';stats.after(ideas);}

async function loadAdminExtras(){const dash=document.querySelector('#admin-dashboard');if(!dash||dash.hidden)return;injectAdminExtras();const count=async table=>{const {count}=await featureDb.from(table).select('*',{count:'exact',head:true});return count??0;};const [events,projects,regs,ideasCount]=await Promise.all([count('events'),count('projects'),count('event_registrations'),count('ideas')]);document.querySelector('#stat-events').textContent=events;document.querySelector('#stat-projects').textContent=projects;document.querySelector('#stat-registrations').textContent=regs;document.querySelector('#stat-ideas').textContent=ideasCount;const box=document.querySelector('#admin-ideas');const {data,error}=await featureDb.from('ideas').select('*').order('created_at',{ascending:false});if(error){box.innerHTML='<p>Tu n’as pas accès aux idées.</p>';return;}box.innerHTML=(data||[]).map(i=>`<div class="admin-row"><div><strong>${fEsc(i.title)}</strong><small>${fEsc(i.category||'Autre')} • ${fEsc(i.first_name||'Anonyme')} • ${new Date(i.created_at).toLocaleDateString('fr-FR')}</small><p>${fEsc(i.description)}</p></div><button class="small-btn danger" data-del-idea="${i.id}">Supprimer</button></div>`).join('')||'<p>Aucune idée reçue.</p>';box.querySelectorAll('[data-del-idea]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Supprimer cette idée ?'))return;await featureDb.from('ideas').delete().eq('id',b.dataset.delIdea);await loadAdminExtras();}));}

function watchAdmin(){const dash=document.querySelector('#admin-dashboard');if(!dash)return;injectAdminExtras();new MutationObserver(()=>{if(!dash.hidden)loadAdminExtras();}).observe(dash,{attributes:true,attributeFilter:['hidden']});if(!dash.hidden)loadAdminExtras();}

document.addEventListener('DOMContentLoaded',()=>{initIdeaBox();initCalendar();watchAdmin();});